### ISSUE TITLE
Fix python versions failing when dont have 3.6 installed

### ISSUE THREAD

**Issue by vladdoster** [patdaburu/cookiecutter-click#11]
When you do not have 3.6 or 3.7 on your actual system the venv fails to build and errors when you choose the version not present. 

I don't have an immediate answer but would love to ask if someone has an idea. I am going to fiddle with it for a bit. Maybe something to run in the post-run hook?

Maybe change to different versioning system that can download python version on the fly? I think I remember using something that did this.

**Comment by patdaburu** [comment]
I have proposed a fix in the post-generation hook in PR https://github.com/patdaburu/cookiecutter-click/pull/18.  If `make venv` fails the hook provides some indication as to why, then fails itself.
