### ISSUE TITLE
Add CI pipeline that run tests on each commit

### ISSUE THREAD

**Issue by vladdoster** [patdaburu/cookiecutter-click#12]
This will help keep up code quality and make sure new contributions are added in a verified manner.

**Comment by patdaburu** [comment]
Also great!

**Comment by vladdoster** [comment]
Sorry for dropping off recently. 

I am going to knock this out. Any chance you could enable Travis integration?

**Comment by patdaburu** [comment]
No worries at all.  Many thanks once again for all your contributions!

I have enabled Travis integration for this repository.  Please let me know if it doesn't behave as expected.

**Comment by vladdoster** [comment]
Working on this. Could you disable travis and enable github actions? Gratzi! :+1:

**Comment by vladdoster** [comment]
Rationale for gh actions is just to see what it's all about. Can always go back to travis if we want. Ideally use gh actions for repo ci and then give project generation a few options.

**Comment by patdaburu** [comment]
Sorry for the delay... just catching up.  We can certainly do this.  (I just have to figure out what I need to do to enable github actions, but am looking into that right now.)

**Comment by vladdoster** [comment]
No worries, I have a working version on my fork. Will open a pr tonight

**Comment by patdaburu** [comment]
It seems that all I needed to do was sign up for the beta.  The repository now has the Actions tab, so I'm thinking it should be good to go.  Let me know if you know of additional steps that are required.
