### ISSUE TITLE
Added CI options for project generation

### ISSUE THREAD

**Issue by vladdoster** [patdaburu/cookiecutter-click#13]
Speaking of CI. . . #12 

This is something I see in a lot of cookiecutter projects. 

A good starting point would be Travis since its tight integration with Github, but I would also like to have CircleCI and maybe Azure Pipelines as options.

**Comment by patdaburu** [comment]
Agreed: This would be great!

**Comment by vladdoster** [comment]
This is going to be a doozy. Diving in.
