### ISSUE TITLE
Add READme badges

### ISSUE THREAD

**Issue by vladdoster** [patdaburu/cookiecutter-click#14]
Everyone loves a riced up github repo.

I propose adding the following badges:

- Build status
- Updates linking to pypy
- A link to issues
- Code style

**Comment by patdaburu** [comment]
I also love a riced up github repo.  Also, speaking of the main page, given all your contributions please consider adding your name to the "Authors" section of the README.md.

**Comment by vladdoster** [comment]
A 'black' code style badge was added in #21

**Comment by vladdoster** [comment]
Closing this

Repo now has a build, pyup, python3, and black style badge. I think this is good. Feel free to reopen if you want something added.
