### ISSUE TITLE
Add to PyPi

### ISSUE THREAD

**Issue by vladdoster** [patdaburu/cookiecutter-click#15]
This would be super helpful to have on Pypi so I can include in scripts and not have to have git on my system. I can just pip install it.

**Comment by patdaburu** [comment]
This sounds good to me, though I have to admit I wasn't aware this was an option for cookiecutters (when I started this one I had the idea that the local file system and github repositories were the only options).  I'd be interested if you have any links that discuss publishing to pypi.
