### ISSUE TITLE
'LICENSE' template references 'open_source_license'.

### ISSUE THREAD

**Issue by patdaburu** [patdaburu/cookiecutter-click#16]
The 'LICENSE' template file references a variable called 'open_source_license' but the cookiecutter config calls it 'license'.  (Personal note:  I wanted to acknowledge that I should have caught that in the review.)

**Comment by patdaburu** [comment]
https://github.com/patdaburu/cookiecutter-click/pull/17

**Comment by vladdoster** [comment]
I think this never got closed. 

Closing now.
