### ISSUE TITLE
.pip-license-ignore interferes with automatic license detection

### ISSUE THREAD

**Issue by joergbrech** [patdaburu/cookiecutter-click#77]
Github uses `licensee` to try to auto-detect the used license. It fails to detect the license text in `LICENSE` for any repo created from this template, because of the file name `.pip-license-ignore`, see licensee/licensee#425.

**Comment by patdaburu** [comment]
Many thanks for this this observation.  I've created a branch that removes the file from the template and issued a PR.

**Comment by patdaburu** [comment]
Thanks again!  The file name in the template is now `.pip-lic-ignore`.
